// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7uCXm8HiDO6gyErutJ9Z2vPShXgjjf8g',
    appId: '1:1001637506211:web:3fa28364ac79e999c62316',
    messagingSenderId: '1001637506211',
    projectId: 'maestros-ad9d0',
    authDomain: 'maestros-ad9d0.firebaseapp.com',
    storageBucket: 'maestros-ad9d0.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyIxE_rXwkZWhoaQmYjilgq1Z1MDmKg2M',
    appId: '1:1001637506211:android:ffd8cf28c70eefc3c62316',
    messagingSenderId: '1001637506211',
    projectId: 'maestros-ad9d0',
    storageBucket: 'maestros-ad9d0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFYUraJa7j5a5c51vMSjr-oumy8zw21hg',
    appId: '1:1001637506211:ios:d23a6aaeacba569cc62316',
    messagingSenderId: '1001637506211',
    projectId: 'maestros-ad9d0',
    storageBucket: 'maestros-ad9d0.firebasestorage.app',
    iosBundleId: 'com.example.marketplaceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCFYUraJa7j5a5c51vMSjr-oumy8zw21hg',
    appId: '1:1001637506211:ios:d23a6aaeacba569cc62316',
    messagingSenderId: '1001637506211',
    projectId: 'maestros-ad9d0',
    storageBucket: 'maestros-ad9d0.firebasestorage.app',
    iosBundleId: 'com.example.marketplaceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC7uCXm8HiDO6gyErutJ9Z2vPShXgjjf8g',
    appId: '1:1001637506211:web:6f22ede832c35f5ec62316',
    messagingSenderId: '1001637506211',
    projectId: 'maestros-ad9d0',
    authDomain: 'maestros-ad9d0.firebaseapp.com',
    storageBucket: 'maestros-ad9d0.firebasestorage.app',
  );
}
